[package]
name = "bum"
version = "0.1.0"
authors = ["Andrew Aldridge <i80and@foxquill.com>"]
build = "build.rs"

[[bin]]
name = "bum"
path = "src/main.rs"

[[bin]]
name = "bum-transcode"
path = "src/bum-transcode/main.rs"

[dependencies]
libc = "0.2"
toml = "0.1"
regex = "0.1"
rustc-serialize = "0.3"
queryst = "0.1"
hyper = "0.7"
url = "0.5"
time = "0.1"
clap = "1.5"

[build-dependencies]
gcc = "0.3"
pkg-config = "0.3"
